language: java
jdk:
  - openjdk11

after_script:
  - mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)
  - ls -R target/dependency
  - docker build . --file Dockerfile --tag glookie/CICD:latest
  - docker push glookie/CICD:latest