language: java
jdk:
  - openjdk11

after_script:
  - mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)
  - docker build . --file Dockerfile --tag glookie/travis_cicd:latest
  - docker push glookie/travis_cicd:latest