language: java
jdk:
  - openjdk11

after_script:
  - mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - echo $(heroku auth:token) | docker login -u "$ HEROKU_USERNAME" --password-stdin registry.heroku.com 
  - docker build . --file Dockerfile --tag $DOCKER_REPO:latest
  - docker tag $DOCKER_REPO:latest registry.heroku.com/$HEROKU_APP_NAME/web
  
 deploy: 
  provider: script 
  script: 
    # push to dockerhub & heroku 
    docker push $DOCKER_REPO:latest;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web; 
  on: 
    branch: master
