language: java
jdk:
  - openjdk11

after_script:
  - mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)
  - docker build . --file Dockerfile --tag glookie/travis_cicd:latest
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker push glookie/travis_cicd:latest