# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -Dserver.port=8080 --file pom.xml
    - name: List files in the repository
      run: |
        mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)
      #  ls ${{ github.workspace }}/target/dependency
    
    #############################
    #- name: docker login
    #  env:
    #    DOCKER_USER: ${{secrets.DOCKER_USER}}
    #    DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    #  run: |
    #    docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag glookie/githubbuild:latest
      
    #- name: Docker Push
    #  run: docker push glookie/githubbuild:latest

    - run: echo "🍏 This job's status is ${{ job.status }}."
      
